## ILDEBRANDO MAGNANI

Homework 7

I'm solving in Python. This code applies the Banach Contraction Mapping Theorem to perform risk neutral asset pricing. The first computational excercise is done under the assumption of homogeneous beliefs, the second one is done in a context of heterogeneous beliefs.

## Excercise 1:

This is the case of homogeneous beliefs. First, I define the primitives - the 2 transition matrices, the initial price function and the dividend function.

In [1]:
import numpy as np

Transition_matrix_1 = np.array([[0.971, 0.029,     0],
                                [0.145, 0.778, 0.077],
                                [    0, 0.508, 0.492]])

Transition_matrix_2 = np.array([[0.871, 0.029,   0.1],
                                [0.145, 0.778, 0.077],
                                [    0, 0.508, 0.492]])

Initial_p = np.array([[1.0],
                      [1.0],
                      [1.0]])

Dividend = np.array([[1.0],
                     [0.0],
                     [0.0]])        

Now I'm going to generate a function that applies the contraction mapping and returns an approximation to the equilibrium price function, through iteration.

In [113]:
def mapping(Transition_matrix, Initial_p, Dividend):
    p = Initial_p
    for i in enumerate(range(max_iteration)): 
        T_p = beta * Transition_matrix @ (p + Dividend)
        diff = T_p - p
        abs_diff = np.absolute(diff)
        max_diff = np.amax(abs_diff)
        if max_diff <= tol:
            ni = i
            break
        p[:] = T_p
    print(ni, 'number of iterations')
    return T_p

We compute the equilibrium using the first transition matrix "Transition_matrix_1".

In [114]:
tol = 0.0001
max_iteration = 10000
beta = 0.98
ni = max_iteration


mapping(Transition_matrix_1, Initial_p, Dividend)

(444, 444) number of iterations


array([[ 40.75493575],
       [ 35.95604382],
       [ 34.56716376]])

As expected, the price is higher when we have a normal growth, as in this state we have dividends. The fact that the mild growth state has a positive probability of direct transition to normal growth - contrary to the negative growth state - makes the equilibrium price in MG higher than the equilibrium price in NG.

We now compute the equilibrium using the second transition matrix "Transition_matrix_2".

In [115]:
tol = 0.0001
max_iteration = 10000
beta = 0.98
ni = max_iteration


mapping(Transition_matrix_2, Initial_p, Dividend)

(400, 400) number of iterations


array([[ 23.50593972],
       [ 21.1036361 ],
       [ 20.28875772]])

Generalized lower equilibrium prices are the results of risk neutral asset pricing. In fact, with the second transition matrix we have a positive probability of direct transition from normal growth to negative growth, which imposes more "weight" on a state which has a dividend of zero. 

## Excercise 2:

(Analytical part)

The proof is very similar to the previous one.

\begin{equation}
\left|\mathbb{T}p(x)\right| \leq \beta \left|\max_{i\in{1,2}} \left[\sum_{y \in S}[d(y) + p(y)]q_{i}(x,y)\right]\right|
\leq \beta \max_{i\in{1,2}} \left[\sum_{y \in S}\left|[d(y) + p(y)]\right| q_{i}(x,y)\right]
\end{equation}

\begin{equation} 
\leq \beta \max_{i\in{1,2}} \sum_{y \in S}[ \lVert\ d(y) \rVert_\infty + \lVert\ p(y) \rVert_\infty] q_{i}(x,y) \leq \beta \max_{i\in{1,2}} (\lVert\ d(y) \rVert_\infty + \lVert\ p(y) \rVert_\infty) \sum_{y \in S}q_{i}(x,y) = \beta (\lVert\ d(y) \rVert_\infty + \lVert\ p(y) \rVert_\infty) S
\end{equation}

Therefore:

\begin{equation}
\left|\mathbb{T}p(x) - \mathbb{T}p'(x)\right| = \left|\beta \max_{i\in{1,2}} \sum_{y \in S}[d(y) + p(y)]q_{i}(x,y) - \beta \max_{i\in{1,2}} \sum_{y \in S}[d(y) + p'(y)]q_{i}(x,y)\right|
\end{equation}

(This step follows from the inequality suggested in the homework sheet)

\begin{equation}
\leq \beta \left|\max_{i\in{1,2}} \left[\sum_{y \in S}[d(y) + p(y)]q_{i}(x,y) - \sum_{y \in S}[d(y) + p'(y)]q_{i}(x,y)\right]\right| \leq \beta \max_{i\in{1,2}} \left|\sum_{y \in S}[p(y) - p'(y)]q_{i}(x,y)\right|
\end{equation}

\begin{equation}
= \beta \max_{i\in{1,2}} \sum_{y \in S} \left|[p(y) - p'(y)]q_{i}(x,y)\right| = \beta \max_{i\in{1,2}} \sum_{y \in S} \left|[p(y) - p'(y)]\right| q_{i}(x,y) = \beta \max_{i\in{1,2}} \sum_{y \in S} \left|[p(y) - p'(y)]\right| q_{i}(x,y)
\end{equation}

\begin{equation}
= \beta \max_{i\in{1,2}} \sum_{y \in S}[ \lVert\ p(y) \rVert_\infty - \lVert\ p'(y) \rVert_\infty]q_{i}(x,y) = \beta \max_{i\in{1,2}} [ \lVert\ p(y) \rVert_\infty - \lVert\ p'(y) \rVert_\infty] \sum_{y \in S}q_{i}(x,y) = \beta [ \lVert\ p(y) \rVert_\infty - \lVert\ p'(y) \rVert_\infty]
\end{equation}


It therefore follows that:

\begin{equation}
\lVert\ \mathbb{T}p(x) - \mathbb{T}p'(x)\rVert_\infty \leq \beta \lVert\ p - p'\rVert_\infty
\end{equation}

since x $ \in $ S was arbitrary. Thus, *T* is a uniform contraction.













## Excercise 3:

This is the case of heterogeneous beliefs. The mapping function is slightly modified to compute the elementwise max of the "price function vector" at each iterative step.

In [116]:
def mapping(Transition_matrix_1, Transition_matrix_2, Initial_p, Dividend):
    p = Initial_p
    for i in enumerate(range(max_iteration)): 
        T_p_1 = beta * Transition_matrix_1 @ (p + Dividend)
        T_p_2 = beta * Transition_matrix_2 @ (p + Dividend)
        T_p = np.maximum(T_p_1, T_p_2)
        diff = T_p - p
        abs_diff = np.absolute(diff)
        max_diff = np.amax(abs_diff)
        if max_diff <= tol:
            ni = i
            break
        p[:] = T_p
    print(ni, 'number of iterations')
    return T_p

In [117]:
tol = 0.0001
max_iteration = 10000
beta = 0.98
ni = max_iteration

mapping(Transition_matrix_1, Transition_matrix_2, Initial_p, Dividend)

(402, 402) number of iterations


array([[ 40.75488598],
       [ 35.95599406],
       [ 34.56711399]])