# Problem Set 7
#### Laszlo Tetenyi

In [1]:
import numpy as np
import matplotlib.pyplot as plt

Create the transition matrices, the beta and the dividends

In [2]:
q1 = np.array([[0.971 , 0.029 ,0],[0.145,0.778,0.077]\
               ,[0,0.508,0.492]])
q2 = np.array([[0.871 , 0.029 ,0.1],[0.145,0.778,0.077]\
               ,[0,0.508,0.492]])
d = np.zeros((3,1))
d[0,0] = 1.0
beta = 0.98

## Exercise 1

In [3]:
def contraction(p,q,d,beta):
    return beta *  q @  (d + p)

In [4]:
def bellman_iter(contraction,q,d,beta,p = None,tol =1e-10):
    if p == None:
        p = np.zeros(d.shape)
    conv = 1
    while conv > tol:
        p_next = contraction(p,q,d,beta)
        conv = np.max(np.abs(p_next - p)) # d_infty
        #print(conv) to check convergence
        np.copyto(p,p_next)
    return p

In [11]:
p_star1 = bellman_iter(contraction,q1,d,beta)
p_star1

array([[ 40.75977457],
       [ 35.96088264],
       [ 34.57200258]])

In [12]:
p_star2 = bellman_iter(contraction,q2,d,beta)
p_star2

array([[ 23.50113472],
       [ 21.09883109],
       [ 20.28395271]])

In [7]:
p_star1 - p_star2

array([[ 17.25863985],
       [ 14.86205155],
       [ 14.28804987]])

Interpretation: As the probability of the recession increases, prices in all states are falling. 

## Exercise 2

Sufficient conditions: 
- the transition probabilities are defined by an ergodic Markov chain
- $ \beta < 1 $
- $d \in b\mathbb{R^S}$
- finite number of beliefs (can be loosened)

##### Proof: 

Take any $x$ $\in S$. 

Step I: T maps a $ p \in b\mathbb{R^S} $ to $ b\mathbb{R^S}$ 
\begin{eqnarray}
|Tp(x)| =& | \beta \max_{i \in {1,2}} \int_{y \in S} (p(y) + d(y)) q_i(x,y) dy | \\
\leq & \beta \max_{i \in {1,2}} \int_{y \in S} |p(y) + d(y)|q_i(x,y) dy  \\
\leq & \beta \max_{i \in {1,2}} \int_{y \in S} ||p + d||_{\infty}q_i(x,y) dy \\
\leq & \beta \max_{i \in {1,2}} \int_{y \in S} ||p||_{\infty} + ||d||_{\infty}q_i(x,y) dy \\
\leq & (||p||_{\infty} + ||d||_{\infty} ) \beta \max_{i \in {1,2}} \int_{y \in S} q_i(x,y) dy \\
= & (||p||_{\infty} + ||d||_{\infty} )\beta
\end{eqnarray}
This is a uniform bound on $T$ for every $x$ so we are done.

Step II: The following chain of reasoning (using the properties of the max) is justified:

\begin{eqnarray}
|Tp(x) - Tp'(x) |  =& | \beta \max_{i \in {1,2}} \int_{y \in S} (p(y) + d(y)) q_i(x,y) dy - \beta \max_{i \in {1,2}} \int_{y \in S} (p'(y) + d(y)) q_i(x,y) dy | \\
\leq & \max_{i \in {1,2}} | \beta  \int_{y \in S} (p(y) + d(y)) q_i(x,y) dy - \beta \int_{y \in S} (p'(y) + d(y)) q_i(x,y) dy | \\
=& \beta \max_{i \in {1,2}} \int_{y \in S} |p(y) - p'(y)|q_i(x,y) dy \\
 \leq & \beta \max_{i \in {1,2}} \int_{y \in S}  ||p - p'||_{\infty}  q_i(x,y) dy \\
 \leq & \beta ||p - p'||_{\infty}  \max_{i \in {1,2}} \int_{y \in S}   q_i(x,y) dy  \\
 = & \beta ||p - p'||_{\infty}
\end{eqnarray}
Therefore we have that
\begin{eqnarray}
||Tp - Tp' ||_{\infty} \leq& \beta ||p - p'||_{\infty}
\end{eqnarray}

So $T$ is a uniform contraction

#### Prove the additional condition that:  $ |\sup_i a_i - \sup_i b_i| \leq \sup_i | a_i - b_i| $
##### Proof:  
\begin{eqnarray}
a_j - \sup_i b_i \leq & a_j - b_j & \forall j  \\
a_j - b_j \leq & \sup_i ( a_i - b_i ) &    \\
a_j - \sup_i b_i \leq & \sup_i ( a_i - b_i ) &  \forall j \\
\sup_j (a_j - \sup_i b_i) \leq & \sup_i ( a_i - b_i ) &  \\
\sup_i a_i - \sup_i b_i \leq & \sup_i ( a_i - b_i ) & 
\end{eqnarray}
where the last line is due to the 3rd line that  $ \sup_i ( a_i - b_i ) $ is an upper bound for $ a_j - \sup_i b_i $ and that $ \sup_i b_i $ is constant in line 4 . Now with similar reasoning you can show that $ \sup_i b_i - \sup_i a_i  \leq \sup_i ( b_i - a_i ) $. As $\sup_i ( a_i - b_i ) \leq \sup_i | a_i - b_i|$ and $\sup_i ( b_i - a_i ) \leq \sup_i | a_i - b_i|$ and either $ \sup_i b_i - \sup_i a_i = |\sup_i a_i - \sup_i b_i| $ or $ \sup_i a_i - \sup_i b_i = |\sup_i a_i - \sup_i b_i| $, proving the claim

## Exercise 3

In [8]:
def contraction_het(p,q1,q2,d,beta):
    return np.maximum(beta *  q1 @ (d + p),beta *  q2 @ (d + p))

In [9]:
def bellman_iter_het(contraction_het,q1,q2,d,beta,p = None,tol =1e-10):
    if p == None:
        p = np.zeros(d.shape)
    conv = 1
    while conv > tol:
        p_next = contraction_het(p,q1,q2,d,beta)
        conv = np.max(np.abs(p_next - p)) # d_infty
        #print(conv) to check convergence
        np.copyto(p,p_next)
    return p

In [10]:
bellman_iter_het(contraction_het,q1,q2,d,beta)

array([[ 40.75977457],
       [ 35.96088264],
       [ 34.57200258]])