# HW #7
# Fixed Point Calculation via Banach Contraction 
## Timothy Petliar
## N12592901





The main step of the proof of the the Banach fixed point theorem is the construction of a Cauchy sequence of functions under the mapping we wish to study. In the follwing excercise we use this idea to approximate an equilibirum price function for an asset. We are given a contraction mapping, and the we repeatly apply it to any bounded function until the uniform norm of the difference of consecutive terms is within some small tolerance. 



In [41]:
import numpy as np
q1=np.array([[0.971, .029, 0.0],[0.145, 0.778, 0.077], [0.0, 0.508, 0.492] ]) #1st transition matrix
div=np.array([[1],[0], [0]]) #dividend function
tol=.001 #tolerance
num_iter=10000 #maximum iterations
beta=0.98  #constant for the contraction mapping


Nothing interesting here. Just the usual boilerplate and basic variable assignment


In [11]:
def uniform_norm(f1, f2): #Calculate the uniform given two functions
    difference=abs(f1-f2)
    norm=np.amax(difference)
    return norm




I calculate the uniform by taking the component-wise absolure differnce of two functions and returing the maximum such value

In [19]:
def contraction(p, transition, dividend):
    T_p=beta *   transition @(p+dividend)
    return T_p


I wrote a seperate function to apply the contraction to p for a given transition matrix and dividend

In [42]:
def equilibrium(transition, dividend, beta, iterations, tolerance): #Inputs
   
    interations=iterations
    p=(np.zeros(transition.shape[0])).reshape(transition.shape[0],1) 
    #Create a vector of all zeros with 1 column of length same as row of a transition matrix
    

    for iteration in range(0,interations):       #apply the contraction  in a loop
        T_p=np.array(contraction(p,transition, dividend))  # calls the contraction function
       
        if iteration >=0 and uniform_norm(T_p, p)<=tolerance:  #test convergence and break loop when accuracy achieved
            break
        if iteration==interations-1:                           #Alert to error
            print("failed to converge")
     
        p[:]=T_p #Being careful to bind to copy of T_p
   
    return T_p  
        

This is the main function in my program. I apply the contraction in a loop and test for convergence.



In [43]:
equilibrium(q1, div, beta, num_iter,tol)

array([[ 40.71110731],
       [ 35.91221539],
       [ 34.52333532]])

Appears to have worked.

We now to run this for the second transisition matrix:

In [44]:
q2= np.array([[0.871 ,0.029 ,0.1], [0.145, 0.778, 0.077], [0.0, 0.508, 0.492]])
equilibrium(q2, div, beta, num_iter,tol)

array([[ 23.45270867],
       [ 21.05040505],
       [ 20.23552666]])

Also appears to work. 


## Heterogeneous Case

Not too different. All we need is to compute the equilibirum with both transisition matrices and select the maximum for each component.

In [48]:
def hetero_equilibrium(transition1,transition2, dividend, beta, iterations, tolerance): #Inputs
   
    interations=iterations
    p=(np.zeros(transition1.shape[0])).reshape(transition1.shape[0],1) 
    #Create a vector of all zeros with 1 column of length same as row of a transition matrix
    

    for iteration in range(0,interations):       #apply the contraction  in a loop
        T_p_1=np.array(contraction(p,transition1, dividend))  # calls the contraction function for 1st matrix
        T_p_2=np.array(contraction(p,transition2, dividend)) #calls the contraction function for 2nd matrix
        T_p=np.maximum(T_p_1, T_p_2)                         #Select componentwise maximum
        if iteration >=0 and uniform_norm(T_p, p)<=tolerance:  #test convergence and break loop when accuracy achieved
            break
        if iteration==interations-1:                           #Alert to error
            print("failed to converge")
     
        p[:]=T_p #Being careful to bind to copy of T_p
   
    return T_p  

In [50]:
hetero_equilibrium(q1, q2, div, beta, num_iter, tol)

array([[ 40.71110731],
       [ 35.91221539],
       [ 34.52333532]])

Interesting. The result is the same as for homogeneous  q1.