## Problem Set 7

**Victoria Gregory**, N14207660

3/28/2016



### Question 1

In this problem set, we compute some equilibrium price functions, $p()$ which satisfy:

$$
p(x) = \beta \displaystyle \sum_{y \in S} [d(y) + p(y)]q(x,y)
$$

where $d(y)$ is a function for dividends in state $y \in S$, $q(x,y)$ is a state transition matrix, and $\beta < 1$ is the discount rate.

To find $p()$, we will start with an initial guess, compute the left-hand side of the above equation as our new guess, and repeat. We stop when the sup-norm of the two guesses is within some tolerance level. The Julia function below implements this method.

In [8]:
function eq_price(beta,d,Q,p_init,tol)
    dist = 1;
    p_guess = p_init;
    while dist > tol
        LHS = beta*Q*(d+p_guess);
        dist = maximum(abs(p_guess-LHS));
        p_guess = LHS;
    end
    return p_guess;
end

eq_price (generic function with 1 method)

Now, I set up the primitives, like the dividend function, $\beta$, and some different $Q$'s, as well as an initial guess for the pricing function and a tolerance level.

In [9]:
d = float([1 0 0])';
beta = 0.98;
Q1 = [0.971 0.029 0; 0.145 0.778 0.077; 0 0.508 0.492];
Q2 = [0.871 0.029 0.1; 0.145 0.778 0.077; 0 0.508 0.492];
p_init = ones(length(d),1);
tol = 0.00000000001;

Now, I evaluate the function for the two different transition matrices.

In [5]:
price1 = eq_price(beta,d,Q1,p_init,tol)

3x1 Array{Float64,2}:
 40.7598
 35.9609
 34.572 

In [6]:
price2 = eq_price(beta,d,Q2,p_init,tol)

3x1 Array{Float64,2}:
 23.5011
 21.0988
 20.284 

### Question 2

In the heterogeneous beliefs case, the equilibrium condition becomes:

$$
p(x) = \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} [d(y) + p(y)]q_i(x,y)
$$

To show there exists a unique solution, we need to prove that $T$:

$$
Tp(x) = \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} [d(y) + p(y)]q_i(x,y)
$$

is a uniform contraction. First assume that $d \in b \mathbb{R}^s$. To show that $T$ maps bounded functions to bounded functions:

\begin{align*}
|Tp(x)| &= \left\lvert \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} [d(y) + p(y)]q_i(x,y) \right\rvert \\
& \leq \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} |d(y) + p(y)|q_i(x,y) \\
& \leq \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} (||d(y)||_{\infty} + ||p(y)||_{\infty})q_i(x,y) \\
& \leq \beta \displaystyle \sum_{y \in S} \left[ \max_{i \in \{1,2\}} (||d(y)||_{\infty} + ||p(y)||_{\infty}) q_i(x,y) \right] \\
& \leq \beta (||d||_{\infty} + ||p||_{\infty})
\end{align*}

which is bounded. 

Now to show that $T$ is a uniform contraction, pick any $p, p' \in b \mathbb{R}^s$ and let $x \in S$.

\begin{align*}
|Tp(x) - Tp'(x)| &= \left\lvert \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} [d(y) + p(y)]q_i(x,y) - \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} [d(y) + p'(y)]q_i(x,y) \right\rvert \\
& \leq \beta \max_{i \in \{1,2\}} \left\lvert \displaystyle \sum_{y \in S} (p(y) - p'(y)) q_i(x,y) \right\rvert \\
& \leq \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} \left\lvert p(y) - p'(y) \right\rvert q_i(x,y) \\
& \leq \beta \max_{i \in \{1,2\}} \displaystyle \sum_{y \in S} ||p - p'||_{\infty} q_i(x,y) \\
& \leq \max \left\{\displaystyle \sum_{y \in S} ||p - p'||_{\infty} q_1(x,y), \displaystyle \sum_{y \in S} ||p - p'||_{\infty} q_2(x,y) \right\} \\
& = \beta ||p-p'||_{\infty}
\end{align*}

#### Proof of the hint:

\begin{align*}
\sup_i |a_i - b_i| & \geq \left\lvert \sup_i(a_i-b_i) \right\rvert \\
& \geq \left\lvert \sup_i(a_i - \sup_j (b_j)) \right\rvert \\
&= \left\lvert \sup_i a_i - \sup_i b_i \right\rvert
\end{align*}

### Question 3

I use the same method as in Problem 1, using the following Julia function:


In [1]:
function eq_price_het(beta,d,Q1,Q2,p_init,tol)
    dist = 1;
    p_guess = p_init;
    while dist > tol
        LHS = beta*max(Q1*(d+p_guess),Q2*(d+p_guess));
        dist = maximum(abs(p_guess-LHS));
        p_guess = LHS;
    end
    return p_guess;
end

eq_price_het (generic function with 1 method)

Using the two transition matrices from Problem 1, I get the following price function:

In [7]:
price_het = eq_price_het(beta,d,Q1,Q2,p_init,tol)

3x1 Array{Float64,2}:
 40.7598
 35.9609
 34.572 

The same as in Problem 1 using matrix $Q_1$.