Carlos Lizama  
N17866309

### Exercise 7

The objective of this exercise is to proyect the vector $\mathbf y$ onto the column space of $\mathbf X$.

First, define the vector $\mathbf y$ and the matrix $\mathbf X$

In [1]:
y = [1, 3, -3]
X = [1 0; 0 -6; 2 2]

3x2 Array{Int64,2}:
 1   0
 0  -6
 2   2

The first way is by using the projection matrix:

In [2]:
P = X*inv(X'*X)*X'
Py1 = P*y

3-element Array{Float64,1}:
 -0.565217
  3.26087 
 -2.21739 

Now I implement the Gram-Schmidt method:

In [3]:
"""
This function receives a matrix X and returns a matrix U with orthonormal columns which generate the same space as X
"""
function GramSchmidt(X)
    n_rows = size(X,1)
    n_columns = size(X,2)
    U = zeros(size(X))
    
    v1 = X[:,1]
    u1 = v1/norm(v1)
    U[:,1] = u1
    
    for i in 2:n_columns
        A = X[:,1:i-1]
        M = eye(n_rows)-A*inv(A'*A)*A'
        vi = M*X[:,i]     # projection of the current column onto the orthogonal space spanned by the previos vectors
        ui = vi/norm(vi)
        U[:,i] = ui
    end
        
    return U
    
end
        

GramSchmidt (generic function with 1 method)

In [4]:
U = GramSchmidt(X)
Py2 = U*U'*y

3-element Array{Float64,1}:
 -0.565217
  3.26087 
 -2.21739 

Finally, I obtain the matrix $\mathbf U$ by using the QR decompsiition routine in Julia

In [5]:
U,R = qr(X)
Py3 = U*U'*y

3-element Array{Float64,1}:
 -0.565217
  3.26087 
 -2.21739 