## Ildebrando Magnani

N16654444

Homework 6

Computational Excercise 7

Part 1: Project a vector y into the column space of a matrix X using the regular expression for
projections:

In [2]:
import numpy as np

y = np.array([1, 3, -3])

X = np.array([[1,  0],
              [0, -6],
              [2,  2]])

P_y = X @ np.linalg.inv(np.transpose(X) @ X) @ np.transpose(X) @ y

print(P_y.reshape(3,1), 'Projection of y onto column space of X')


[[-0.56521739]
 [ 3.26086957]
 [-2.2173913 ]] Projection of y onto column space of X








Part 2: Project a vector y into the column space of a matrix X using Gram-Schmidt process:

In [3]:
y = np.array([1, 3, -3])

X = np.array([[1,  0],
              [0, -6],
              [2,  2]])

number_of_cols = len(X[1,:])


def proj_y_onto_X(matrix):
    for col in range(number_of_cols):
        if col == 0:
            M = np.identity(len(X[:,0]))
            v_1 = M @ X[:,0:1]
            u_1 = v_1 / np.sqrt(np.transpose(v_1) @ v_1)
            Ort_basis = u_1   
        else:
            Spn = X[:,0:col]
            P = Spn @ np.linalg.inv(np.transpose(Spn) @ Spn) @ np.transpose(Spn)
            M = np.identity(len(X[:,0])) - P
            v_i = M @ X[:,col:col+1]
            u_i = v_i / np.sqrt(np.transpose(v_i) @ v_i)
            Ort_basis = np.hstack((Ort_basis, u_i))

    P_y = Ort_basis @ np.transpose(Ort_basis) @ y
    return Ort_basis, P_y.reshape(len(X[:,0]),1)

Orthonormal_Basis, Proj_y = proj_y_onto_X(X)

print(Orthonormal_Basis, 'Orthonormal Basis')
print(Proj_y, 'Projection of y onto column space of X')
    

[[ 0.4472136  -0.13187609]
 [ 0.         -0.98907071]
 [ 0.89442719  0.06593805]] Orthonormal Basis
[[-0.56521739]
 [ 3.26086957]
 [-2.2173913 ]] Projection of y onto column space of X







Part 3: Project a vector y into the column space of a matrix X using Q-R factorization:

In [4]:
y = np.array([1, 3, -3])

X = np.array([[1,  0],
              [0, -6],
              [2,  2]])

q, r = np.linalg.qr(X)
P_y = q @ np.transpose(q) @ y

print(q, 'Orthonormal Basis')
print(P_y.reshape(3,1), 'Projection of y onto column space of X')

[[-0.4472136  -0.13187609]
 [-0.         -0.98907071]
 [-0.89442719  0.06593805]] Orthonormal Basis
[[-0.56521739]
 [ 3.26086957]
 [-2.2173913 ]] Projection of y onto column space of X


We see that the three different methods all produce the same result for the projection of y onto the column space of X, as expected.