# Exercise 7 - Projection


Use:
- projection $P = X(X'X)^{-1}X' $
- Gram-Schmidt to convert $X $ to $U $ and then $U U'$
- Q-R to convert $X $ to $U $ and then $U U'$

In [1]:
import numpy as np

In [2]:
y = np.reshape([1,3,-3],(3,1))
X = np.reshape([[1,0],[0,-6],[2,2]],(3,2))

### 1) Projection

In [3]:
X @ np.linalg.inv(X.transpose() @ X) @ X.transpose() @ y

array([[-0.56521739],
       [ 3.26086957],
       [-2.2173913 ]])

### 2) Gram-Schmidt

In [4]:
def gram_schmidt(X):
    M = np.eye(X.shape[0])
    V = np.empty(X.shape)
    U = np.empty(X.shape)
    for i in range(X.shape[1]):
        V[:,i] = M @ X[:,i]
        P_next = X[:,0:(i+1)] @ np.linalg.inv(X[:,0:(i+1)].transpose() @ X[:,0:(i+1)]) @ X[:,0:(i+1)].transpose()
        M_next = np.eye(X.shape[0]) - P_next
        np.copyto(M,M_next)
        U[:,i] = V[:,i] / np.linalg.norm(V[:,i])
    return U

In [5]:
U = gram_schmidt(X)

Check if it is really working by normalizing and checking the dot product

In [6]:
np.sum(np.multiply(U[:,0,None],U[:,1,None]))

-2.7755575615628914e-17

In [7]:
np.linalg.norm(U[:,1])

1.0

Now evaluate the projection

In [8]:
U @ U.transpose() @ y  # Indeed, same answer

array([[-0.56521739],
       [ 3.26086957],
       [-2.2173913 ]])

### 3) Q-R

In [9]:
from scipy.linalg import qr 

In [10]:
Q , R = qr(X,mode='economic')

In [11]:
Q @ Q.transpose() @ y  #same answer

array([[-0.56521739],
       [ 3.26086957],
       [-2.2173913 ]])