## Problem Set 6: Computational Exercise

**Victoria Gregory, N14207660**

3/15/2016

In this homework, we are going to project a vector $y$ onto the column space of matrix $X$ in Julia with three different methods. Let's first set up our vectors.

In [1]:
y = [1; 3; -3];
X = [1 0; 0 -6; 2 2];

---
**Part 1**: Using the familiar formula
$$Py = X(X'X)^{-1}X'y$$

In [3]:
P = X*(X'*X)^(-1)*X';
proj1 = P*y

3-element Array{Float64,1}:
 -0.565217
  3.26087 
 -2.21739 

---
**Part 2**: Gram-Schmidt orthogonalization

First, we need to construct $U$, the matrix with orthonormal columns that has the same column space as $X$. I follow the procedure from the notes:

In [6]:
U = zeros(size(X))
for i=1:size(X,2)
    xi = X[:,i]
    if i==1
        M = eye(size(X,1))
    else
        Si = X[:,1:i-1]
        P = Si*(Si'*Si)^(-1)*Si'
        M = eye(size(X,1)) - P
    end
    vi = M*xi
    ui = vi/norm(vi)
    U[:,i] = ui
end

Once we have $U$, all we need to do is use the formula: $Py = UU'y$.

In [7]:
proj2 = U*U'*y

3-element Array{Float64,1}:
 -0.565217
  3.26087 
 -2.21739 

We get the same answer as in Part 1.

---
**Part 3**: QR decomposition

I used Julia's built-in routine for the QR decomposition.

In [16]:
F = qrfact(X);
R = full(F[:R]);
Q = full(F[:Q]);
proj3 = X*R^(-1)*Q'*y 

3-element Array{Float64,1}:
 -0.565217
  3.26087 
 -2.21739 

Again, I get the same answer as Parts 1 and 2!